/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pruebas.entity;


import java.math.BigDecimal;

/**
 * Sic1idenpersId generated by hbm2java
 */
public class Sic1idenpersId  implements java.io.Serializable {


     private BigDecimal idTipoiden;
     private String codIden;

    public Sic1idenpersId() {
    }

    public Sic1idenpersId(BigDecimal idTipoiden, String codIden) {
       this.idTipoiden = idTipoiden;
       this.codIden = codIden;
    }
   
    public BigDecimal getIdTipoiden() {
        return this.idTipoiden;
    }
    
    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }




}


